// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  worldId: __t.string().name("world_id"),
  commitId: __t.string().name("commit_id"),
  intentId: __t.string().name("intent_id"),
  wallet: __t.string(),
  actionType: __t.i32().name("action_type"),
  q: __t.i32(),
  r: __t.i32(),
  tick: __t.i64(),
  accepted: __t.bool(),
  reason: __t.string(),
  includeTileDelta: __t.bool().name("include_tile_delta"),
  previousTerrain: __t.i32().name("previous_terrain"),
  nextTerrain: __t.i32().name("next_terrain"),
  previousBuilding: __t.i32().name("previous_building"),
  nextBuilding: __t.i32().name("next_building"),
  ownerChanged: __t.bool().name("owner_changed"),
  ownerWallet: __t.string().name("owner_wallet"),
  lastUpdatedTick: __t.i64().name("last_updated_tick"),
  ownedTilesDelta: __t.i32().name("owned_tiles_delta"),
  sustainabilityScoreDelta: __t.i32().name("sustainability_score_delta"),
  actionsTakenDelta: __t.i32().name("actions_taken_delta"),
  actionsRemainingDelta: __t.i32().name("actions_remaining_delta"),
  woodDelta: __t.i32().name("wood_delta"),
  foodDelta: __t.i32().name("food_delta"),
  mineralsDelta: __t.i32().name("minerals_delta"),
  forestDelta: __t.i32().name("forest_delta"),
  carbonDelta: __t.i32().name("carbon_delta"),
  actionCount: __t.i32().name("action_count"),
  batchHash: __t.string().name("batch_hash"),
  committedAtMs: __t.i64().name("committed_at_ms"),
});
