// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  wallet: __t.string().primaryKey(),
  usernameNormalized: __t.string().name("username_normalized"),
  username: __t.string(),
  displayName: __t.string().name("display_name"),
  createdAtMs: __t.i64().name("created_at_ms"),
  updatedAtMs: __t.i64().name("updated_at_ms"),
});
