// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  wallet: __t.string().primaryKey(),
  wood: __t.i32(),
  food: __t.i32(),
  minerals: __t.i32(),
  researchPoints: __t.i32().name("research_points"),
  ownedTiles: __t.i32().name("owned_tiles"),
  sustainabilityScore: __t.i32().name("sustainability_score"),
  actionsTaken: __t.i32().name("actions_taken"),
  ecoActions: __t.i32().name("eco_actions"),
  industrialActions: __t.i32().name("industrial_actions"),
  agricultureActions: __t.i32().name("agriculture_actions"),
  techBasicForestry: __t.i32().name("tech_basic_forestry"),
  techRenewableEnergy: __t.i32().name("tech_renewable_energy"),
  techCarbonCapture: __t.i32().name("tech_carbon_capture"),
  reputation: __t.string(),
  actionsThisCycle: __t.i32().name("actions_this_cycle"),
  lastClientSeq: __t.i64().name("last_client_seq"),
  lastCycle: __t.i64().name("last_cycle"),
  forestTiles: __t.i32().name("forest_tiles"),
  farmlandTiles: __t.i32().name("farmland_tiles"),
  settlementCount: __t.i32().name("settlement_count"),
  industryCount: __t.i32().name("industry_count"),
  recoveryProjectCount: __t.i32().name("recovery_project_count"),
  passiveFoodProgressMilli: __t.i32().name("passive_food_progress_milli"),
  passiveMineralProgressMilli: __t.i32().name("passive_mineral_progress_milli"),
});
