// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  wallet: __t.string(),
  intentIds: __t.array(__t.string()),
  clientSeqs: __t.array(__t.i64()),
  actionTypes: __t.array(__t.i32()),
  qs: __t.array(__t.i32()),
  rs: __t.array(__t.i32()),
};
