// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i64().primaryKey(),
  q: __t.i32(),
  r: __t.i32(),
  terrain: __t.i32(),
  building: __t.i32(),
  owner: __t.string(),
  miningCount: __t.i32().name("mining_count"),
  lastUpdate: __t.i64().name("last_update"),
});
