// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.string(),
  giveWood: __t.i32().name("give_wood"),
  giveFood: __t.i32().name("give_food"),
  giveMinerals: __t.i32().name("give_minerals"),
  wantWood: __t.i32().name("want_wood"),
  wantFood: __t.i32().name("want_food"),
  wantMinerals: __t.i32().name("want_minerals"),
  status: __t.i32(),
  expiresTick: __t.i64().name("expires_tick"),
  acceptedBy: __t.string().name("accepted_by"),
});
