// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActionCommitEventRow = __t.object("ActionCommitEventRow", {
  worldId: __t.string(),
  commitId: __t.string(),
  intentId: __t.string(),
  wallet: __t.string(),
  actionType: __t.i32(),
  q: __t.i32(),
  r: __t.i32(),
  tick: __t.i64(),
  accepted: __t.bool(),
  reason: __t.string(),
  includeTileDelta: __t.bool(),
  previousTerrain: __t.i32(),
  nextTerrain: __t.i32(),
  previousBuilding: __t.i32(),
  nextBuilding: __t.i32(),
  ownerChanged: __t.bool(),
  ownerWallet: __t.string(),
  lastUpdatedTick: __t.i64(),
  ownedTilesDelta: __t.i32(),
  sustainabilityScoreDelta: __t.i32(),
  actionsTakenDelta: __t.i32(),
  actionsRemainingDelta: __t.i32(),
  woodDelta: __t.i32(),
  foodDelta: __t.i32(),
  mineralsDelta: __t.i32(),
  forestDelta: __t.i32(),
  carbonDelta: __t.i32(),
  actionCount: __t.i32(),
  batchHash: __t.string(),
  committedAtMs: __t.i64(),
});
export type ActionCommitEventRow = __Infer<typeof ActionCommitEventRow>;

export const ArmyRow = __t.object("ArmyRow", {
  id: __t.u64(),
  owner: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  lastMoveTick: __t.i64(),
});
export type ArmyRow = __Infer<typeof ArmyRow>;

export const ClimateEventRow = __t.object("ClimateEventRow", {
  id: __t.u64(),
  type: __t.i32(),
  startTick: __t.i64(),
  endTick: __t.i64(),
});
export type ClimateEventRow = __Infer<typeof ClimateEventRow>;

export const CredentialAccountRow = __t.object("CredentialAccountRow", {
  usernameNormalized: __t.string(),
  wallet: __t.string(),
  username: __t.string(),
  displayName: __t.string(),
  passwordSalt: __t.string(),
  passwordHash: __t.string(),
  createdAtMs: __t.i64(),
  updatedAtMs: __t.i64(),
});
export type CredentialAccountRow = __Infer<typeof CredentialAccountRow>;

export const CredentialAuthResult = __t.object("CredentialAuthResult", {
  success: __t.bool(),
  created: __t.bool(),
  error: __t.string(),
  wallet: __t.string(),
  username: __t.string(),
  displayName: __t.string(),
});
export type CredentialAuthResult = __Infer<typeof CredentialAuthResult>;

export const CycleClockRow = __t.object("CycleClockRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CycleClockRow = __Infer<typeof CycleClockRow>;

export const PactRow = __t.object("PactRow", {
  id: __t.u64(),
  type: __t.i32(),
  walletA: __t.string(),
  walletB: __t.string(),
  status: __t.i32(),
  createdAt: __t.i64(),
});
export type PactRow = __Infer<typeof PactRow>;

export const PlayerIdentityRow = __t.object("PlayerIdentityRow", {
  wallet: __t.string(),
  usernameNormalized: __t.string(),
  username: __t.string(),
  displayName: __t.string(),
  createdAtMs: __t.i64(),
  updatedAtMs: __t.i64(),
});
export type PlayerIdentityRow = __Infer<typeof PlayerIdentityRow>;

export const PlayerRow = __t.object("PlayerRow", {
  wallet: __t.string(),
  wood: __t.i32(),
  food: __t.i32(),
  minerals: __t.i32(),
  researchPoints: __t.i32(),
  ownedTiles: __t.i32(),
  sustainabilityScore: __t.i32(),
  actionsTaken: __t.i32(),
  ecoActions: __t.i32(),
  industrialActions: __t.i32(),
  agricultureActions: __t.i32(),
  techBasicForestry: __t.i32(),
  techRenewableEnergy: __t.i32(),
  techCarbonCapture: __t.i32(),
  reputation: __t.string(),
  actionsThisCycle: __t.i32(),
  lastClientSeq: __t.i64(),
  lastCycle: __t.i64(),
  forestTiles: __t.i32(),
  farmlandTiles: __t.i32(),
  settlementCount: __t.i32(),
  industryCount: __t.i32(),
  recoveryProjectCount: __t.i32(),
  passiveFoodProgressMilli: __t.i32(),
  passiveMineralProgressMilli: __t.i32(),
});
export type PlayerRow = __Infer<typeof PlayerRow>;

export const RecoveryCandidateRow = __t.object("RecoveryCandidateRow", {
  tileId: __t.i64(),
  q: __t.i32(),
  r: __t.i32(),
  recoverAtTick: __t.i64(),
});
export type RecoveryCandidateRow = __Infer<typeof RecoveryCandidateRow>;

export const RecoveryQueueRow = __t.object("RecoveryQueueRow", {
  id: __t.i64(),
  q: __t.i32(),
  r: __t.i32(),
  recoverAtTick: __t.i64(),
});
export type RecoveryQueueRow = __Infer<typeof RecoveryQueueRow>;

export const TileRow = __t.object("TileRow", {
  id: __t.i64(),
  q: __t.i32(),
  r: __t.i32(),
  terrain: __t.i32(),
  building: __t.i32(),
  owner: __t.string(),
  miningCount: __t.i32(),
  lastUpdate: __t.i64(),
});
export type TileRow = __Infer<typeof TileRow>;

export const TradeOfferRow = __t.object("TradeOfferRow", {
  id: __t.u64(),
  owner: __t.string(),
  giveWood: __t.i32(),
  giveFood: __t.i32(),
  giveMinerals: __t.i32(),
  wantWood: __t.i32(),
  wantFood: __t.i32(),
  wantMinerals: __t.i32(),
  status: __t.i32(),
  expiresTick: __t.i64(),
  acceptedBy: __t.string(),
});
export type TradeOfferRow = __Infer<typeof TradeOfferRow>;

export const WorldStateRow = __t.object("WorldStateRow", {
  worldId: __t.string(),
  tick: __t.i64(),
  cycle: __t.i64(),
  rngState: __t.i64(),
  forestTotal: __t.i32(),
  carbonTotal: __t.i32(),
  initialForest: __t.i32(),
  carbonCap: __t.i32(),
  recoveryIndexBuilt: __t.bool(),
});
export type WorldStateRow = __Infer<typeof WorldStateRow>;

