/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TokenSyncBatcherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "carbonToken"
      | "forestToken"
      | "mintInitial"
      | "owner"
      | "setTokens"
      | "syncBoth"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BatchSynced" | "InitialMinted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "carbonToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forestToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintInitial",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setTokens",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "syncBoth",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "carbonToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forestToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintInitial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setTokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "syncBoth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BatchSyncedEvent {
  export type InputTuple = [
    cycleId: BigNumberish,
    forestDelta: BigNumberish,
    carbonDelta: BigNumberish
  ];
  export type OutputTuple = [
    cycleId: bigint,
    forestDelta: bigint,
    carbonDelta: bigint
  ];
  export interface OutputObject {
    cycleId: bigint;
    forestDelta: bigint;
    carbonDelta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitialMintedEvent {
  export type InputTuple = [
    forestTotal: BigNumberish,
    carbonTotal: BigNumberish
  ];
  export type OutputTuple = [forestTotal: bigint, carbonTotal: bigint];
  export interface OutputObject {
    forestTotal: bigint;
    carbonTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenSyncBatcher extends BaseContract {
  connect(runner?: ContractRunner | null): TokenSyncBatcher;
  waitForDeployment(): Promise<this>;

  interface: TokenSyncBatcherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  carbonToken: TypedContractMethod<[], [string], "view">;

  forestToken: TypedContractMethod<[], [string], "view">;

  mintInitial: TypedContractMethod<
    [
      forestTotal: BigNumberish,
      carbonTotal: BigNumberish,
      relayAddr: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setTokens: TypedContractMethod<
    [_forestToken: AddressLike, _carbonToken: AddressLike],
    [void],
    "nonpayable"
  >;

  syncBoth: TypedContractMethod<
    [
      cycleId: BigNumberish,
      forestDelta: BigNumberish,
      carbonDelta: BigNumberish,
      relayAddr: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "carbonToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forestToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mintInitial"
  ): TypedContractMethod<
    [
      forestTotal: BigNumberish,
      carbonTotal: BigNumberish,
      relayAddr: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTokens"
  ): TypedContractMethod<
    [_forestToken: AddressLike, _carbonToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "syncBoth"
  ): TypedContractMethod<
    [
      cycleId: BigNumberish,
      forestDelta: BigNumberish,
      carbonDelta: BigNumberish,
      relayAddr: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BatchSynced"
  ): TypedContractEvent<
    BatchSyncedEvent.InputTuple,
    BatchSyncedEvent.OutputTuple,
    BatchSyncedEvent.OutputObject
  >;
  getEvent(
    key: "InitialMinted"
  ): TypedContractEvent<
    InitialMintedEvent.InputTuple,
    InitialMintedEvent.OutputTuple,
    InitialMintedEvent.OutputObject
  >;

  filters: {
    "BatchSynced(uint64,int256,int256)": TypedContractEvent<
      BatchSyncedEvent.InputTuple,
      BatchSyncedEvent.OutputTuple,
      BatchSyncedEvent.OutputObject
    >;
    BatchSynced: TypedContractEvent<
      BatchSyncedEvent.InputTuple,
      BatchSyncedEvent.OutputTuple,
      BatchSyncedEvent.OutputObject
    >;

    "InitialMinted(int256,int256)": TypedContractEvent<
      InitialMintedEvent.InputTuple,
      InitialMintedEvent.OutputTuple,
      InitialMintedEvent.OutputObject
    >;
    InitialMinted: TypedContractEvent<
      InitialMintedEvent.InputTuple,
      InitialMintedEvent.OutputTuple,
      InitialMintedEvent.OutputObject
    >;
  };
}
