/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GlobalCountersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitCycle"
      | "cycles"
      | "lastCycleId"
      | "owner"
      | "relay"
      | "renounceOwnership"
      | "setRelay"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CycleCommitted" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitCycle",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cycles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastCycleId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "relay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRelay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cycles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastCycleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CycleCommittedEvent {
  export type InputTuple = [
    cycleId: BigNumberish,
    forestDelta: BigNumberish,
    carbonDelta: BigNumberish,
    forestTotal: BigNumberish,
    carbonTotal: BigNumberish,
    actionBatchHash: BytesLike,
    actionCount: BigNumberish
  ];
  export type OutputTuple = [
    cycleId: bigint,
    forestDelta: bigint,
    carbonDelta: bigint,
    forestTotal: bigint,
    carbonTotal: bigint,
    actionBatchHash: string,
    actionCount: bigint
  ];
  export interface OutputObject {
    cycleId: bigint;
    forestDelta: bigint;
    carbonDelta: bigint;
    forestTotal: bigint;
    carbonTotal: bigint;
    actionBatchHash: string;
    actionCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GlobalCounters extends BaseContract {
  connect(runner?: ContractRunner | null): GlobalCounters;
  waitForDeployment(): Promise<this>;

  interface: GlobalCountersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitCycle: TypedContractMethod<
    [
      cycleId: BigNumberish,
      forestDelta: BigNumberish,
      carbonDelta: BigNumberish,
      actionBatchHash: BytesLike,
      actionCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  cycles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        cycleId: bigint;
        forestDelta: bigint;
        carbonDelta: bigint;
        forestTotal: bigint;
        carbonTotal: bigint;
        actionBatchHash: string;
        actionCount: bigint;
        committedAt: bigint;
      }
    ],
    "view"
  >;

  lastCycleId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  relay: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRelay: TypedContractMethod<[_relay: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitCycle"
  ): TypedContractMethod<
    [
      cycleId: BigNumberish,
      forestDelta: BigNumberish,
      carbonDelta: BigNumberish,
      actionBatchHash: BytesLike,
      actionCount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cycles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string, bigint, bigint] & {
        cycleId: bigint;
        forestDelta: bigint;
        carbonDelta: bigint;
        forestTotal: bigint;
        carbonTotal: bigint;
        actionBatchHash: string;
        actionCount: bigint;
        committedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastCycleId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relay"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRelay"
  ): TypedContractMethod<[_relay: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CycleCommitted"
  ): TypedContractEvent<
    CycleCommittedEvent.InputTuple,
    CycleCommittedEvent.OutputTuple,
    CycleCommittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CycleCommitted(uint64,int256,int256,int256,int256,bytes32,uint32)": TypedContractEvent<
      CycleCommittedEvent.InputTuple,
      CycleCommittedEvent.OutputTuple,
      CycleCommittedEvent.OutputObject
    >;
    CycleCommitted: TypedContractEvent<
      CycleCommittedEvent.InputTuple,
      CycleCommittedEvent.OutputTuple,
      CycleCommittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
