// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CredentialLoginProcedure from "../credential_login_procedure";
import * as CredentialSignupProcedure from "../credential_signup_procedure";
import * as EnsureSeedCredentialAccountProcedure from "../ensure_seed_credential_account_procedure";

export type CredentialLoginArgs = __Infer<typeof CredentialLoginProcedure.params>;
export type CredentialLoginResult = __Infer<typeof CredentialLoginProcedure.returnType>;
export type CredentialSignupArgs = __Infer<typeof CredentialSignupProcedure.params>;
export type CredentialSignupResult = __Infer<typeof CredentialSignupProcedure.returnType>;
export type EnsureSeedCredentialAccountArgs = __Infer<typeof EnsureSeedCredentialAccountProcedure.params>;
export type EnsureSeedCredentialAccountResult = __Infer<typeof EnsureSeedCredentialAccountProcedure.returnType>;

