// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ArmyMoveReducer from "../army_move_reducer";
import ArmySpawnReducer from "../army_spawn_reducer";
import EnsurePlayerReducer from "../ensure_player_reducer";
import PactAcceptReducer from "../pact_accept_reducer";
import PactCancelReducer from "../pact_cancel_reducer";
import PactCreateReducer from "../pact_create_reducer";
import ResearchTechReducer from "../research_tech_reducer";
import SeedDefaultWorldReducer from "../seed_default_world_reducer";
import SeedWorldReducer from "../seed_world_reducer";
import SubmitIntentReducer from "../submit_intent_reducer";
import SubmitIntentBatchReducer from "../submit_intent_batch_reducer";
import TradeAcceptReducer from "../trade_accept_reducer";
import TradeCancelReducer from "../trade_cancel_reducer";
import TradeCreateReducer from "../trade_create_reducer";

export type ArmyMoveParams = __Infer<typeof ArmyMoveReducer>;
export type ArmySpawnParams = __Infer<typeof ArmySpawnReducer>;
export type EnsurePlayerParams = __Infer<typeof EnsurePlayerReducer>;
export type PactAcceptParams = __Infer<typeof PactAcceptReducer>;
export type PactCancelParams = __Infer<typeof PactCancelReducer>;
export type PactCreateParams = __Infer<typeof PactCreateReducer>;
export type ResearchTechParams = __Infer<typeof ResearchTechReducer>;
export type SeedDefaultWorldParams = __Infer<typeof SeedDefaultWorldReducer>;
export type SeedWorldParams = __Infer<typeof SeedWorldReducer>;
export type SubmitIntentParams = __Infer<typeof SubmitIntentReducer>;
export type SubmitIntentBatchParams = __Infer<typeof SubmitIntentBatchReducer>;
export type TradeAcceptParams = __Infer<typeof TradeAcceptReducer>;
export type TradeCancelParams = __Infer<typeof TradeCancelReducer>;
export type TradeCreateParams = __Infer<typeof TradeCreateReducer>;

