// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
// Adapted for com.clockworklabs.spacetimedbsdk v1.1.1 (installed SDK).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        internal RemoteReducers(DbConnection conn) : base(conn) { }
        internal event Action<ReducerEventContext, Exception>? InternalOnUnhandledReducerError;
    }

    public sealed class RemoteProcedures : RemoteBase
    {
        internal RemoteProcedures(DbConnection conn) : base(conn) { }
    }

    public sealed partial class RemoteTables : RemoteTablesBase
    {
        public RemoteTables(DbConnection conn)
        {
            AddTable(ActionCommitEvents = new(conn));
            AddTable(Armies = new(conn));
            AddTable(ClimateEvents = new(conn));
            AddTable(Pacts = new(conn));
            AddTable(PlayerIdentities = new(conn));
            AddTable(Players = new(conn));
            AddTable(Tiles = new(conn));
            AddTable(TradeOffers = new(conn));
            AddTable(WorldState = new(conn));
        }
    }

    public interface IRemoteDbContext
        : IDbContext<RemoteTables, RemoteReducers, SubscriptionBuilder, RemoteProcedures>
    {
        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError;
    }

    public sealed class EventContext : IEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        public readonly Event<Reducer> Event;

        public RemoteTables Db => conn.Db;
        public RemoteReducers Reducers => conn.Reducers;
        public RemoteProcedures Procedures => conn.Procedures;
        public bool IsActive => conn.IsActive;
        public void Disconnect() => conn.Disconnect();
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        public Identity? Identity => conn.Identity;
        public ConnectionId ConnectionId => conn.ConnectionId;

        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal EventContext(DbConnection conn, Event<Reducer> Event)
        {
            this.conn = conn;
            this.Event = Event;
        }
    }

    public sealed class ReducerEventContext : IReducerEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        public readonly ReducerEvent<Reducer> Event;

        public RemoteTables Db => conn.Db;
        public RemoteReducers Reducers => conn.Reducers;
        public RemoteProcedures Procedures => conn.Procedures;
        public bool IsActive => conn.IsActive;
        public void Disconnect() => conn.Disconnect();
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        public Identity? Identity => conn.Identity;
        public ConnectionId ConnectionId => conn.ConnectionId;

        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal ReducerEventContext(DbConnection conn, ReducerEvent<Reducer> reducerEvent)
        {
            this.conn = conn;
            Event = reducerEvent;
        }
    }

    public sealed class ErrorContext : IErrorContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        public readonly Exception Event;
        Exception IErrorContext.Event => Event;

        public RemoteTables Db => conn.Db;
        public RemoteReducers Reducers => conn.Reducers;
        public RemoteProcedures Procedures => conn.Procedures;
        public bool IsActive => conn.IsActive;
        public void Disconnect() => conn.Disconnect();
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        public Identity? Identity => conn.Identity;
        public ConnectionId ConnectionId => conn.ConnectionId;

        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal ErrorContext(DbConnection conn, Exception error)
        {
            this.conn = conn;
            Event = error;
        }
    }

    public sealed class SubscriptionEventContext : ISubscriptionEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;

        public RemoteTables Db => conn.Db;
        public RemoteReducers Reducers => conn.Reducers;
        public RemoteProcedures Procedures => conn.Procedures;
        public bool IsActive => conn.IsActive;
        public void Disconnect() => conn.Disconnect();
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        public Identity? Identity => conn.Identity;
        public ConnectionId ConnectionId => conn.ConnectionId;

        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal SubscriptionEventContext(DbConnection conn)
        {
            this.conn = conn;
        }
    }

    public sealed class ProcedureEventContext : IProcedureEventContext, IRemoteDbContext
    {
        private readonly DbConnection conn;
        public readonly ProcedureEvent Event;

        public RemoteTables Db => conn.Db;
        public RemoteReducers Reducers => conn.Reducers;
        public RemoteProcedures Procedures => conn.Procedures;
        public bool IsActive => conn.IsActive;
        public void Disconnect() => conn.Disconnect();
        public SubscriptionBuilder SubscriptionBuilder() => conn.SubscriptionBuilder();
        public Identity? Identity => conn.Identity;
        public ConnectionId ConnectionId => conn.ConnectionId;

        public event Action<ReducerEventContext, Exception>? OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }

        internal ProcedureEventContext(DbConnection conn, ProcedureEvent procedureEvent)
        {
            this.conn = conn;
            Event = procedureEvent;
        }
    }

    public sealed class SubscriptionBuilder
    {
        private readonly IDbConnection conn;
        private event Action<SubscriptionEventContext>? Applied;
        private event Action<ErrorContext, Exception>? Error;

        public SubscriptionBuilder(IDbConnection conn) { this.conn = conn; }

        public SubscriptionBuilder OnApplied(Action<SubscriptionEventContext> callback) { Applied += callback; return this; }
        public SubscriptionBuilder OnError(Action<ErrorContext, Exception> callback) { Error += callback; return this; }

        public SubscriptionHandle Subscribe(string[] querySqls) => new(conn, Applied, Error, querySqls);

        public SubscriptionHandle SubscribeToAllTables() => Subscribe(new[]
        {
            "SELECT * FROM action_commit_events", "SELECT * FROM armies",
            "SELECT * FROM climate_events", "SELECT * FROM pacts",
            "SELECT * FROM player_identities", "SELECT * FROM players",
            "SELECT * FROM tiles", "SELECT * FROM trade_offers", "SELECT * FROM world_state",
        });
    }

    public sealed class SubscriptionHandle : SubscriptionHandleBase<SubscriptionEventContext, ErrorContext>
    {
        public SubscriptionHandle(IDbConnection conn, Action<SubscriptionEventContext>? onApplied,
            Action<ErrorContext, Exception>? onError, string[] querySqls)
            : base(conn, onApplied, onError, querySqls) { }
    }

    public abstract partial class Reducer { private Reducer() { } }

    public sealed class DbConnection : DbConnectionBase<DbConnection, RemoteTables, Reducer>
    {
        public override RemoteTables Db { get; }
        public readonly RemoteReducers Reducers;
        public readonly RemoteProcedures Procedures;

        public DbConnection()
        {
            Db = new(this);
            Reducers = new(this);
            Procedures = new(this);
        }

        protected override IEventContext ToEventContext(Event<Reducer> Event) => new EventContext(this, Event);
        protected override IReducerEventContext ToReducerEventContext(ReducerEvent<Reducer> reducerEvent) => new ReducerEventContext(this, reducerEvent);
        protected override ISubscriptionEventContext MakeSubscriptionEventContext() => new SubscriptionEventContext(this);
        protected override IErrorContext ToErrorContext(Exception exception) => new ErrorContext(this, exception);
        protected override IProcedureEventContext ToProcedureEventContext(ProcedureEvent procedureEvent) => new ProcedureEventContext(this, procedureEvent);

        protected override bool Dispatch(IReducerEventContext context, Reducer reducer)
        {
            var ctx = (ReducerEventContext)context;
            return reducer switch
            {
                Reducer.ArmyMove args       => Reducers.InvokeArmyMove(ctx, args),
                Reducer.ArmySpawn args      => Reducers.InvokeArmySpawn(ctx, args),
                Reducer.EnsurePlayer args   => Reducers.InvokeEnsurePlayer(ctx, args),
                Reducer.PactAccept args     => Reducers.InvokePactAccept(ctx, args),
                Reducer.PactCancel args     => Reducers.InvokePactCancel(ctx, args),
                Reducer.PactCreate args     => Reducers.InvokePactCreate(ctx, args),
                Reducer.ResearchTech args   => Reducers.InvokeResearchTech(ctx, args),
                Reducer.SeedDefaultWorld args => Reducers.InvokeSeedDefaultWorld(ctx, args),
                Reducer.SeedWorld args      => Reducers.InvokeSeedWorld(ctx, args),
                Reducer.SubmitIntent args   => Reducers.InvokeSubmitIntent(ctx, args),
                Reducer.SubmitIntentBatch args => Reducers.InvokeSubmitIntentBatch(ctx, args),
                Reducer.TradeAccept args    => Reducers.InvokeTradeAccept(ctx, args),
                Reducer.TradeCancel args    => Reducers.InvokeTradeCancel(ctx, args),
                Reducer.TradeCreate args    => Reducers.InvokeTradeCreate(ctx, args),
                _ => throw new ArgumentOutOfRangeException("Reducer", $"Unknown reducer {reducer}")
            };
        }

        public SubscriptionBuilder SubscriptionBuilder() => new(this);

        public event Action<ReducerEventContext, Exception> OnUnhandledReducerError
        {
            add => Reducers.InternalOnUnhandledReducerError += value;
            remove => Reducers.InternalOnUnhandledReducerError -= value;
        }
    }
}
