// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActionCommitEventsHandle : RemoteTableHandle<EventContext, ActionCommitEventRow>
        {
            protected override string RemoteTableName => "action_commit_events";

            internal ActionCommitEventsHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ActionCommitEventsHandle ActionCommitEvents;
    }
}
