// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClimateEventsHandle : RemoteTableHandle<EventContext, ClimateEventRow>
        {
            protected override string RemoteTableName => "climate_events";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClimateEventRow row) => row.Id;

                public IdUniqueIndex(ClimateEventsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ClimateEventsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ClimateEventRow row) => row.Id;
        }

        public readonly ClimateEventsHandle ClimateEvents;
    }
}
