// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PactsHandle : RemoteTableHandle<EventContext, PactRow>
        {
            protected override string RemoteTableName => "pacts";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PactRow row) => row.Id;

                public IdUniqueIndex(PactsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PactsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PactRow row) => row.Id;
        }

        public readonly PactsHandle Pacts;
    }
}
