// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayersHandle : RemoteTableHandle<EventContext, PlayerRow>
        {
            protected override string RemoteTableName => "players";

            public sealed class WalletUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerRow row) => row.Wallet;

                public WalletUniqueIndex(PlayersHandle table) : base(table) { }
            }

            public readonly WalletUniqueIndex Wallet;

            internal PlayersHandle(DbConnection conn) : base(conn)
            {
                Wallet = new(this);
            }

            protected override object GetPrimaryKey(PlayerRow row) => row.Wallet;
        }

        public readonly PlayersHandle Players;
    }
}
