// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerIdentitiesHandle : RemoteTableHandle<EventContext, PlayerIdentityRow>
        {
            protected override string RemoteTableName => "player_identities";

            public sealed class UsernameNormalizedUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerIdentityRow row) => row.UsernameNormalized;

                public UsernameNormalizedUniqueIndex(PlayerIdentitiesHandle table) : base(table) { }
            }

            public readonly UsernameNormalizedUniqueIndex UsernameNormalized;

            public sealed class WalletUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerIdentityRow row) => row.Wallet;

                public WalletUniqueIndex(PlayerIdentitiesHandle table) : base(table) { }
            }

            public readonly WalletUniqueIndex Wallet;

            internal PlayerIdentitiesHandle(DbConnection conn) : base(conn)
            {
                UsernameNormalized = new(this);
                Wallet = new(this);
            }

            protected override object GetPrimaryKey(PlayerIdentityRow row) => row.Wallet;
        }

        public readonly PlayerIdentitiesHandle PlayerIdentities;
    }
}
