// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TilesHandle : RemoteTableHandle<EventContext, TileRow>
        {
            protected override string RemoteTableName => "tiles";

            public sealed class IdUniqueIndex : UniqueIndexBase<long>
            {
                protected override long GetKey(TileRow row) => row.Id;

                public IdUniqueIndex(TilesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TilesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TileRow row) => row.Id;
        }

        public readonly TilesHandle Tiles;
    }
}
