// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TradeOffersHandle : RemoteTableHandle<EventContext, TradeOfferRow>
        {
            protected override string RemoteTableName => "trade_offers";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TradeOfferRow row) => row.Id;

                public IdUniqueIndex(TradeOffersHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TradeOffersHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TradeOfferRow row) => row.Id;
        }

        public readonly TradeOffersHandle TradeOffers;
    }
}
