// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class WorldStateHandle : RemoteTableHandle<EventContext, WorldStateRow>
        {
            protected override string RemoteTableName => "world_state";

            public sealed class WorldIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(WorldStateRow row) => row.WorldId;

                public WorldIdUniqueIndex(WorldStateHandle table) : base(table) { }
            }

            public readonly WorldIdUniqueIndex WorldId;

            internal WorldStateHandle(DbConnection conn) : base(conn)
            {
                WorldId = new(this);
            }

            protected override object GetPrimaryKey(WorldStateRow row) => row.WorldId;
        }

        public readonly WorldStateHandle WorldState;
    }
}
