/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICarbonToken,
  ICarbonTokenInterface,
} from "../../../contracts/TokenSyncBatcher.sol/ICarbonToken";

const _abi = [
  {
    inputs: [],
    name: "lastSyncedCycle",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "cycleId",
        type: "uint64",
      },
      {
        internalType: "int256",
        name: "carbonDelta",
        type: "int256",
      },
      {
        internalType: "address",
        name: "relayAddr",
        type: "address",
      },
    ],
    name: "syncCarbon",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICarbonToken__factory {
  static readonly abi = _abi;
  static createInterface(): ICarbonTokenInterface {
    return new Interface(_abi) as ICarbonTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICarbonToken {
    return new Contract(address, _abi, runner) as unknown as ICarbonToken;
  }
}
