/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IForestToken,
  IForestTokenInterface,
} from "../../../contracts/TokenSyncBatcher.sol/IForestToken";

const _abi = [
  {
    inputs: [],
    name: "lastSyncedCycle",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "cycleId",
        type: "uint64",
      },
      {
        internalType: "int256",
        name: "forestDelta",
        type: "int256",
      },
      {
        internalType: "address",
        name: "relayAddr",
        type: "address",
      },
    ],
    name: "syncForest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IForestToken__factory {
  static readonly abi = _abi;
  static createInterface(): IForestTokenInterface {
    return new Interface(_abi) as IForestTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IForestToken {
    return new Contract(address, _abi, runner) as unknown as IForestToken;
  }
}
