// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActionCommitEventRow
    {
        [DataMember(Name = "world_id")]
        public string WorldId;
        [DataMember(Name = "commit_id")]
        public string CommitId;
        [DataMember(Name = "intent_id")]
        public string IntentId;
        [DataMember(Name = "wallet")]
        public string Wallet;
        [DataMember(Name = "action_type")]
        public int ActionType;
        [DataMember(Name = "q")]
        public int Q;
        [DataMember(Name = "r")]
        public int R;
        [DataMember(Name = "tick")]
        public long Tick;
        [DataMember(Name = "accepted")]
        public bool Accepted;
        [DataMember(Name = "reason")]
        public string Reason;
        [DataMember(Name = "include_tile_delta")]
        public bool IncludeTileDelta;
        [DataMember(Name = "previous_terrain")]
        public int PreviousTerrain;
        [DataMember(Name = "next_terrain")]
        public int NextTerrain;
        [DataMember(Name = "previous_building")]
        public int PreviousBuilding;
        [DataMember(Name = "next_building")]
        public int NextBuilding;
        [DataMember(Name = "owner_changed")]
        public bool OwnerChanged;
        [DataMember(Name = "owner_wallet")]
        public string OwnerWallet;
        [DataMember(Name = "last_updated_tick")]
        public long LastUpdatedTick;
        [DataMember(Name = "owned_tiles_delta")]
        public int OwnedTilesDelta;
        [DataMember(Name = "sustainability_score_delta")]
        public int SustainabilityScoreDelta;
        [DataMember(Name = "actions_taken_delta")]
        public int ActionsTakenDelta;
        [DataMember(Name = "actions_remaining_delta")]
        public int ActionsRemainingDelta;
        [DataMember(Name = "wood_delta")]
        public int WoodDelta;
        [DataMember(Name = "food_delta")]
        public int FoodDelta;
        [DataMember(Name = "minerals_delta")]
        public int MineralsDelta;
        [DataMember(Name = "forest_delta")]
        public int ForestDelta;
        [DataMember(Name = "carbon_delta")]
        public int CarbonDelta;
        [DataMember(Name = "action_count")]
        public int ActionCount;
        [DataMember(Name = "batch_hash")]
        public string BatchHash;
        [DataMember(Name = "committed_at_ms")]
        public long CommittedAtMs;

        public ActionCommitEventRow(
            string WorldId,
            string CommitId,
            string IntentId,
            string Wallet,
            int ActionType,
            int Q,
            int R,
            long Tick,
            bool Accepted,
            string Reason,
            bool IncludeTileDelta,
            int PreviousTerrain,
            int NextTerrain,
            int PreviousBuilding,
            int NextBuilding,
            bool OwnerChanged,
            string OwnerWallet,
            long LastUpdatedTick,
            int OwnedTilesDelta,
            int SustainabilityScoreDelta,
            int ActionsTakenDelta,
            int ActionsRemainingDelta,
            int WoodDelta,
            int FoodDelta,
            int MineralsDelta,
            int ForestDelta,
            int CarbonDelta,
            int ActionCount,
            string BatchHash,
            long CommittedAtMs
        )
        {
            this.WorldId = WorldId;
            this.CommitId = CommitId;
            this.IntentId = IntentId;
            this.Wallet = Wallet;
            this.ActionType = ActionType;
            this.Q = Q;
            this.R = R;
            this.Tick = Tick;
            this.Accepted = Accepted;
            this.Reason = Reason;
            this.IncludeTileDelta = IncludeTileDelta;
            this.PreviousTerrain = PreviousTerrain;
            this.NextTerrain = NextTerrain;
            this.PreviousBuilding = PreviousBuilding;
            this.NextBuilding = NextBuilding;
            this.OwnerChanged = OwnerChanged;
            this.OwnerWallet = OwnerWallet;
            this.LastUpdatedTick = LastUpdatedTick;
            this.OwnedTilesDelta = OwnedTilesDelta;
            this.SustainabilityScoreDelta = SustainabilityScoreDelta;
            this.ActionsTakenDelta = ActionsTakenDelta;
            this.ActionsRemainingDelta = ActionsRemainingDelta;
            this.WoodDelta = WoodDelta;
            this.FoodDelta = FoodDelta;
            this.MineralsDelta = MineralsDelta;
            this.ForestDelta = ForestDelta;
            this.CarbonDelta = CarbonDelta;
            this.ActionCount = ActionCount;
            this.BatchHash = BatchHash;
            this.CommittedAtMs = CommittedAtMs;
        }

        public ActionCommitEventRow()
        {
            this.WorldId = "";
            this.CommitId = "";
            this.IntentId = "";
            this.Wallet = "";
            this.Reason = "";
            this.OwnerWallet = "";
            this.BatchHash = "";
        }
    }
}
