// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ArmyRow
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public string Owner;
        [DataMember(Name = "q")]
        public int Q;
        [DataMember(Name = "r")]
        public int R;
        [DataMember(Name = "last_move_tick")]
        public long LastMoveTick;

        public ArmyRow(
            ulong Id,
            string Owner,
            int Q,
            int R,
            long LastMoveTick
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.Q = Q;
            this.R = R;
            this.LastMoveTick = LastMoveTick;
        }

        public ArmyRow()
        {
            this.Owner = "";
        }
    }
}
