// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClimateEventRow
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "type")]
        public int Type;
        [DataMember(Name = "start_tick")]
        public long StartTick;
        [DataMember(Name = "end_tick")]
        public long EndTick;

        public ClimateEventRow(
            ulong Id,
            int Type,
            long StartTick,
            long EndTick
        )
        {
            this.Id = Id;
            this.Type = Type;
            this.StartTick = StartTick;
            this.EndTick = EndTick;
        }

        public ClimateEventRow()
        {
        }
    }
}
