// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CredentialAccountRow
    {
        [DataMember(Name = "username_normalized")]
        public string UsernameNormalized;
        [DataMember(Name = "wallet")]
        public string Wallet;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "password_salt")]
        public string PasswordSalt;
        [DataMember(Name = "password_hash")]
        public string PasswordHash;
        [DataMember(Name = "created_at_ms")]
        public long CreatedAtMs;
        [DataMember(Name = "updated_at_ms")]
        public long UpdatedAtMs;

        public CredentialAccountRow(
            string UsernameNormalized,
            string Wallet,
            string Username,
            string DisplayName,
            string PasswordSalt,
            string PasswordHash,
            long CreatedAtMs,
            long UpdatedAtMs
        )
        {
            this.UsernameNormalized = UsernameNormalized;
            this.Wallet = Wallet;
            this.Username = Username;
            this.DisplayName = DisplayName;
            this.PasswordSalt = PasswordSalt;
            this.PasswordHash = PasswordHash;
            this.CreatedAtMs = CreatedAtMs;
            this.UpdatedAtMs = UpdatedAtMs;
        }

        public CredentialAccountRow()
        {
            this.UsernameNormalized = "";
            this.Wallet = "";
            this.Username = "";
            this.DisplayName = "";
            this.PasswordSalt = "";
            this.PasswordHash = "";
        }
    }
}
