// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CredentialAuthResult
    {
        [DataMember(Name = "success")]
        public bool Success;
        [DataMember(Name = "created")]
        public bool Created;
        [DataMember(Name = "error")]
        public string Error;
        [DataMember(Name = "wallet")]
        public string Wallet;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "display_name")]
        public string DisplayName;

        public CredentialAuthResult(
            bool Success,
            bool Created,
            string Error,
            string Wallet,
            string Username,
            string DisplayName
        )
        {
            this.Success = Success;
            this.Created = Created;
            this.Error = Error;
            this.Wallet = Wallet;
            this.Username = Username;
            this.DisplayName = DisplayName;
        }

        public CredentialAuthResult()
        {
            this.Error = "";
            this.Wallet = "";
            this.Username = "";
            this.DisplayName = "";
        }
    }
}
