// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PactRow
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "type")]
        public int Type;
        [DataMember(Name = "wallet_a")]
        public string WalletA;
        [DataMember(Name = "wallet_b")]
        public string WalletB;
        [DataMember(Name = "status")]
        public int Status;
        [DataMember(Name = "created_at")]
        public long CreatedAt;

        public PactRow(
            ulong Id,
            int Type,
            string WalletA,
            string WalletB,
            int Status,
            long CreatedAt
        )
        {
            this.Id = Id;
            this.Type = Type;
            this.WalletA = WalletA;
            this.WalletB = WalletB;
            this.Status = Status;
            this.CreatedAt = CreatedAt;
        }

        public PactRow()
        {
            this.WalletA = "";
            this.WalletB = "";
        }
    }
}
