// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerIdentityRow
    {
        [DataMember(Name = "wallet")]
        public string Wallet;
        [DataMember(Name = "username_normalized")]
        public string UsernameNormalized;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "display_name")]
        public string DisplayName;
        [DataMember(Name = "created_at_ms")]
        public long CreatedAtMs;
        [DataMember(Name = "updated_at_ms")]
        public long UpdatedAtMs;

        public PlayerIdentityRow(
            string Wallet,
            string UsernameNormalized,
            string Username,
            string DisplayName,
            long CreatedAtMs,
            long UpdatedAtMs
        )
        {
            this.Wallet = Wallet;
            this.UsernameNormalized = UsernameNormalized;
            this.Username = Username;
            this.DisplayName = DisplayName;
            this.CreatedAtMs = CreatedAtMs;
            this.UpdatedAtMs = UpdatedAtMs;
        }

        public PlayerIdentityRow()
        {
            this.Wallet = "";
            this.UsernameNormalized = "";
            this.Username = "";
            this.DisplayName = "";
        }
    }
}
