// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerRow
    {
        [DataMember(Name = "wallet")]
        public string Wallet;
        [DataMember(Name = "wood")]
        public int Wood;
        [DataMember(Name = "food")]
        public int Food;
        [DataMember(Name = "minerals")]
        public int Minerals;
        [DataMember(Name = "research_points")]
        public int ResearchPoints;
        [DataMember(Name = "owned_tiles")]
        public int OwnedTiles;
        [DataMember(Name = "sustainability_score")]
        public int SustainabilityScore;
        [DataMember(Name = "actions_taken")]
        public int ActionsTaken;
        [DataMember(Name = "eco_actions")]
        public int EcoActions;
        [DataMember(Name = "industrial_actions")]
        public int IndustrialActions;
        [DataMember(Name = "agriculture_actions")]
        public int AgricultureActions;
        [DataMember(Name = "tech_basic_forestry")]
        public int TechBasicForestry;
        [DataMember(Name = "tech_renewable_energy")]
        public int TechRenewableEnergy;
        [DataMember(Name = "tech_carbon_capture")]
        public int TechCarbonCapture;
        [DataMember(Name = "reputation")]
        public string Reputation;
        [DataMember(Name = "actions_this_cycle")]
        public int ActionsThisCycle;
        [DataMember(Name = "last_client_seq")]
        public long LastClientSeq;
        [DataMember(Name = "last_cycle")]
        public long LastCycle;
        [DataMember(Name = "forest_tiles")]
        public int ForestTiles;
        [DataMember(Name = "farmland_tiles")]
        public int FarmlandTiles;
        [DataMember(Name = "settlement_count")]
        public int SettlementCount;
        [DataMember(Name = "industry_count")]
        public int IndustryCount;
        [DataMember(Name = "recovery_project_count")]
        public int RecoveryProjectCount;
        [DataMember(Name = "passive_food_progress_milli")]
        public int PassiveFoodProgressMilli;
        [DataMember(Name = "passive_mineral_progress_milli")]
        public int PassiveMineralProgressMilli;

        public PlayerRow(
            string Wallet,
            int Wood,
            int Food,
            int Minerals,
            int ResearchPoints,
            int OwnedTiles,
            int SustainabilityScore,
            int ActionsTaken,
            int EcoActions,
            int IndustrialActions,
            int AgricultureActions,
            int TechBasicForestry,
            int TechRenewableEnergy,
            int TechCarbonCapture,
            string Reputation,
            int ActionsThisCycle,
            long LastClientSeq,
            long LastCycle,
            int ForestTiles,
            int FarmlandTiles,
            int SettlementCount,
            int IndustryCount,
            int RecoveryProjectCount,
            int PassiveFoodProgressMilli,
            int PassiveMineralProgressMilli
        )
        {
            this.Wallet = Wallet;
            this.Wood = Wood;
            this.Food = Food;
            this.Minerals = Minerals;
            this.ResearchPoints = ResearchPoints;
            this.OwnedTiles = OwnedTiles;
            this.SustainabilityScore = SustainabilityScore;
            this.ActionsTaken = ActionsTaken;
            this.EcoActions = EcoActions;
            this.IndustrialActions = IndustrialActions;
            this.AgricultureActions = AgricultureActions;
            this.TechBasicForestry = TechBasicForestry;
            this.TechRenewableEnergy = TechRenewableEnergy;
            this.TechCarbonCapture = TechCarbonCapture;
            this.Reputation = Reputation;
            this.ActionsThisCycle = ActionsThisCycle;
            this.LastClientSeq = LastClientSeq;
            this.LastCycle = LastCycle;
            this.ForestTiles = ForestTiles;
            this.FarmlandTiles = FarmlandTiles;
            this.SettlementCount = SettlementCount;
            this.IndustryCount = IndustryCount;
            this.RecoveryProjectCount = RecoveryProjectCount;
            this.PassiveFoodProgressMilli = PassiveFoodProgressMilli;
            this.PassiveMineralProgressMilli = PassiveMineralProgressMilli;
        }

        public PlayerRow()
        {
            this.Wallet = "";
            this.Reputation = "";
        }
    }
}
