// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RecoveryQueueRow
    {
        [DataMember(Name = "id")]
        public long Id;
        [DataMember(Name = "q")]
        public int Q;
        [DataMember(Name = "r")]
        public int R;
        [DataMember(Name = "recover_at_tick")]
        public long RecoverAtTick;

        public RecoveryQueueRow(
            long Id,
            int Q,
            int R,
            long RecoverAtTick
        )
        {
            this.Id = Id;
            this.Q = Q;
            this.R = R;
            this.RecoverAtTick = RecoverAtTick;
        }

        public RecoveryQueueRow()
        {
        }
    }
}
