// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TileRow
    {
        [DataMember(Name = "id")]
        public long Id;
        [DataMember(Name = "q")]
        public int Q;
        [DataMember(Name = "r")]
        public int R;
        [DataMember(Name = "terrain")]
        public int Terrain;
        [DataMember(Name = "building")]
        public int Building;
        [DataMember(Name = "owner")]
        public string Owner;
        [DataMember(Name = "mining_count")]
        public int MiningCount;
        [DataMember(Name = "last_update")]
        public long LastUpdate;

        public TileRow(
            long Id,
            int Q,
            int R,
            int Terrain,
            int Building,
            string Owner,
            int MiningCount,
            long LastUpdate
        )
        {
            this.Id = Id;
            this.Q = Q;
            this.R = R;
            this.Terrain = Terrain;
            this.Building = Building;
            this.Owner = Owner;
            this.MiningCount = MiningCount;
            this.LastUpdate = LastUpdate;
        }

        public TileRow()
        {
            this.Owner = "";
        }
    }
}
