// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TradeOfferRow
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "owner")]
        public string Owner;
        [DataMember(Name = "give_wood")]
        public int GiveWood;
        [DataMember(Name = "give_food")]
        public int GiveFood;
        [DataMember(Name = "give_minerals")]
        public int GiveMinerals;
        [DataMember(Name = "want_wood")]
        public int WantWood;
        [DataMember(Name = "want_food")]
        public int WantFood;
        [DataMember(Name = "want_minerals")]
        public int WantMinerals;
        [DataMember(Name = "status")]
        public int Status;
        [DataMember(Name = "expires_tick")]
        public long ExpiresTick;
        [DataMember(Name = "accepted_by")]
        public string AcceptedBy;

        public TradeOfferRow(
            ulong Id,
            string Owner,
            int GiveWood,
            int GiveFood,
            int GiveMinerals,
            int WantWood,
            int WantFood,
            int WantMinerals,
            int Status,
            long ExpiresTick,
            string AcceptedBy
        )
        {
            this.Id = Id;
            this.Owner = Owner;
            this.GiveWood = GiveWood;
            this.GiveFood = GiveFood;
            this.GiveMinerals = GiveMinerals;
            this.WantWood = WantWood;
            this.WantFood = WantFood;
            this.WantMinerals = WantMinerals;
            this.Status = Status;
            this.ExpiresTick = ExpiresTick;
            this.AcceptedBy = AcceptedBy;
        }

        public TradeOfferRow()
        {
            this.Owner = "";
            this.AcceptedBy = "";
        }
    }
}
