// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldStateRow
    {
        [DataMember(Name = "world_id")]
        public string WorldId;
        [DataMember(Name = "tick")]
        public long Tick;
        [DataMember(Name = "cycle")]
        public long Cycle;
        [DataMember(Name = "rng_state")]
        public long RngState;
        [DataMember(Name = "forest_total")]
        public int ForestTotal;
        [DataMember(Name = "carbon_total")]
        public int CarbonTotal;
        [DataMember(Name = "initial_forest")]
        public int InitialForest;
        [DataMember(Name = "carbon_cap")]
        public int CarbonCap;
        [DataMember(Name = "recovery_index_built")]
        public bool RecoveryIndexBuilt;

        public WorldStateRow(
            string WorldId,
            long Tick,
            long Cycle,
            long RngState,
            int ForestTotal,
            int CarbonTotal,
            int InitialForest,
            int CarbonCap,
            bool RecoveryIndexBuilt
        )
        {
            this.WorldId = WorldId;
            this.Tick = Tick;
            this.Cycle = Cycle;
            this.RngState = RngState;
            this.ForestTotal = ForestTotal;
            this.CarbonTotal = CarbonTotal;
            this.InitialForest = InitialForest;
            this.CarbonCap = CarbonCap;
            this.RecoveryIndexBuilt = RecoveryIndexBuilt;
        }

        public WorldStateRow()
        {
            this.WorldId = "";
        }
    }
}
