// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ArmyMoveHandler(ReducerEventContext ctx, ulong armyId, string owner, int q, int r);
        public event ArmyMoveHandler? OnArmyMove;

        public void ArmyMove(ulong armyId, string owner, int q, int r)
        {
            conn.InternalCallReducer(new Reducer.ArmyMove(armyId, owner, q, r));
        }

        public bool InvokeArmyMove(ReducerEventContext ctx, Reducer.ArmyMove args)
        {
            if (OnArmyMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnArmyMove(
                ctx,
                args.ArmyId,
                args.Owner,
                args.Q,
                args.R
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ArmyMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "army_id")]
            public ulong ArmyId;
            [DataMember(Name = "owner")]
            public string Owner;
            [DataMember(Name = "q")]
            public int Q;
            [DataMember(Name = "r")]
            public int R;

            public ArmyMove(
                ulong ArmyId,
                string Owner,
                int Q,
                int R
            )
            {
                this.ArmyId = ArmyId;
                this.Owner = Owner;
                this.Q = Q;
                this.R = R;
            }

            public ArmyMove()
            {
                this.Owner = "";
            }

            string IReducerArgs.ReducerName => "army_move";
        }
    }
}
