// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ArmySpawnHandler(ReducerEventContext ctx, string owner, int q, int r);
        public event ArmySpawnHandler? OnArmySpawn;

        public void ArmySpawn(string owner, int q, int r)
        {
            conn.InternalCallReducer(new Reducer.ArmySpawn(owner, q, r));
        }

        public bool InvokeArmySpawn(ReducerEventContext ctx, Reducer.ArmySpawn args)
        {
            if (OnArmySpawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnArmySpawn(
                ctx,
                args.Owner,
                args.Q,
                args.R
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ArmySpawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "owner")]
            public string Owner;
            [DataMember(Name = "q")]
            public int Q;
            [DataMember(Name = "r")]
            public int R;

            public ArmySpawn(
                string Owner,
                int Q,
                int R
            )
            {
                this.Owner = Owner;
                this.Q = Q;
                this.R = R;
            }

            public ArmySpawn()
            {
                this.Owner = "";
            }

            string IReducerArgs.ReducerName => "army_spawn";
        }
    }
}
