// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnsurePlayerHandler(ReducerEventContext ctx, string wallet);
        public event EnsurePlayerHandler? OnEnsurePlayer;

        public void EnsurePlayer(string wallet)
        {
            conn.InternalCallReducer(new Reducer.EnsurePlayer(wallet));
        }

        public bool InvokeEnsurePlayer(ReducerEventContext ctx, Reducer.EnsurePlayer args)
        {
            if (OnEnsurePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnsurePlayer(
                ctx,
                args.Wallet
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnsurePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "wallet")]
            public string Wallet;

            public EnsurePlayer(string Wallet)
            {
                this.Wallet = Wallet;
            }

            public EnsurePlayer()
            {
                this.Wallet = "";
            }

            string IReducerArgs.ReducerName => "ensure_player";
        }
    }
}
