// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PactAcceptHandler(ReducerEventContext ctx, ulong pactId, string accepter);
        public event PactAcceptHandler? OnPactAccept;

        public void PactAccept(ulong pactId, string accepter)
        {
            conn.InternalCallReducer(new Reducer.PactAccept(pactId, accepter));
        }

        public bool InvokePactAccept(ReducerEventContext ctx, Reducer.PactAccept args)
        {
            if (OnPactAccept == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPactAccept(
                ctx,
                args.PactId,
                args.Accepter
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PactAccept : Reducer, IReducerArgs
        {
            [DataMember(Name = "pact_id")]
            public ulong PactId;
            [DataMember(Name = "accepter")]
            public string Accepter;

            public PactAccept(
                ulong PactId,
                string Accepter
            )
            {
                this.PactId = PactId;
                this.Accepter = Accepter;
            }

            public PactAccept()
            {
                this.Accepter = "";
            }

            string IReducerArgs.ReducerName => "pact_accept";
        }
    }
}
