// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PactCreateHandler(ReducerEventContext ctx, int type, string walletA, string walletB);
        public event PactCreateHandler? OnPactCreate;

        public void PactCreate(int type, string walletA, string walletB)
        {
            conn.InternalCallReducer(new Reducer.PactCreate(type, walletA, walletB));
        }

        public bool InvokePactCreate(ReducerEventContext ctx, Reducer.PactCreate args)
        {
            if (OnPactCreate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPactCreate(
                ctx,
                args.Type,
                args.WalletA,
                args.WalletB
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PactCreate : Reducer, IReducerArgs
        {
            [DataMember(Name = "type")]
            public int Type;
            [DataMember(Name = "wallet_a")]
            public string WalletA;
            [DataMember(Name = "wallet_b")]
            public string WalletB;

            public PactCreate(
                int Type,
                string WalletA,
                string WalletB
            )
            {
                this.Type = Type;
                this.WalletA = WalletA;
                this.WalletB = WalletB;
            }

            public PactCreate()
            {
                this.WalletA = "";
                this.WalletB = "";
            }

            string IReducerArgs.ReducerName => "pact_create";
        }
    }
}
