// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PactCancelHandler(ReducerEventContext ctx, ulong pactId, string requester);
        public event PactCancelHandler? OnPactCancel;

        public void PactCancel(ulong pactId, string requester)
        {
            conn.InternalCallReducer(new Reducer.PactCancel(pactId, requester));
        }

        public bool InvokePactCancel(ReducerEventContext ctx, Reducer.PactCancel args)
        {
            if (OnPactCancel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPactCancel(
                ctx,
                args.PactId,
                args.Requester
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PactCancel : Reducer, IReducerArgs
        {
            [DataMember(Name = "pact_id")]
            public ulong PactId;
            [DataMember(Name = "requester")]
            public string Requester;

            public PactCancel(
                ulong PactId,
                string Requester
            )
            {
                this.PactId = PactId;
                this.Requester = Requester;
            }

            public PactCancel()
            {
                this.Requester = "";
            }

            string IReducerArgs.ReducerName => "pact_cancel";
        }
    }
}
