// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResearchTechHandler(ReducerEventContext ctx, string wallet, int techIndex);
        public event ResearchTechHandler? OnResearchTech;

        public void ResearchTech(string wallet, int techIndex)
        {
            conn.InternalCallReducer(new Reducer.ResearchTech(wallet, techIndex));
        }

        public bool InvokeResearchTech(ReducerEventContext ctx, Reducer.ResearchTech args)
        {
            if (OnResearchTech == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResearchTech(
                ctx,
                args.Wallet,
                args.TechIndex
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResearchTech : Reducer, IReducerArgs
        {
            [DataMember(Name = "wallet")]
            public string Wallet;
            [DataMember(Name = "tech_index")]
            public int TechIndex;

            public ResearchTech(
                string Wallet,
                int TechIndex
            )
            {
                this.Wallet = Wallet;
                this.TechIndex = TechIndex;
            }

            public ResearchTech()
            {
                this.Wallet = "";
            }

            string IReducerArgs.ReducerName => "research_tech";
        }
    }
}
