// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SeedWorldHandler(ReducerEventContext ctx, string tilesJson);
        public event SeedWorldHandler? OnSeedWorld;

        public void SeedWorld(string tilesJson)
        {
            conn.InternalCallReducer(new Reducer.SeedWorld(tilesJson));
        }

        public bool InvokeSeedWorld(ReducerEventContext ctx, Reducer.SeedWorld args)
        {
            if (OnSeedWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSeedWorld(
                ctx,
                args.TilesJson
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SeedWorld : Reducer, IReducerArgs
        {
            [DataMember(Name = "tiles_json")]
            public string TilesJson;

            public SeedWorld(string TilesJson)
            {
                this.TilesJson = TilesJson;
            }

            public SeedWorld()
            {
                this.TilesJson = "";
            }

            string IReducerArgs.ReducerName => "seed_world";
        }
    }
}
