// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SeedDefaultWorldHandler(ReducerEventContext ctx);
        public event SeedDefaultWorldHandler? OnSeedDefaultWorld;

        public void SeedDefaultWorld()
        {
            conn.InternalCallReducer(new Reducer.SeedDefaultWorld());
        }

        public bool InvokeSeedDefaultWorld(ReducerEventContext ctx, Reducer.SeedDefaultWorld args)
        {
            if (OnSeedDefaultWorld == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSeedDefaultWorld(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SeedDefaultWorld : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "seed_default_world";
        }
    }
}
