// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SubmitIntentBatchHandler(ReducerEventContext ctx, string wallet, System.Collections.Generic.List<string> intentIds, System.Collections.Generic.List<long> clientSeqs, System.Collections.Generic.List<int> actionTypes, System.Collections.Generic.List<int> qs, System.Collections.Generic.List<int> rs);
        public event SubmitIntentBatchHandler? OnSubmitIntentBatch;

        public void SubmitIntentBatch(string wallet, System.Collections.Generic.List<string> intentIds, System.Collections.Generic.List<long> clientSeqs, System.Collections.Generic.List<int> actionTypes, System.Collections.Generic.List<int> qs, System.Collections.Generic.List<int> rs)
        {
            conn.InternalCallReducer(new Reducer.SubmitIntentBatch(wallet, intentIds, clientSeqs, actionTypes, qs, rs));
        }

        public bool InvokeSubmitIntentBatch(ReducerEventContext ctx, Reducer.SubmitIntentBatch args)
        {
            if (OnSubmitIntentBatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSubmitIntentBatch(
                ctx,
                args.Wallet,
                args.IntentIds,
                args.ClientSeqs,
                args.ActionTypes,
                args.Qs,
                args.Rs
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SubmitIntentBatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "wallet")]
            public string Wallet;
            [DataMember(Name = "intent_ids")]
            public System.Collections.Generic.List<string> IntentIds;
            [DataMember(Name = "client_seqs")]
            public System.Collections.Generic.List<long> ClientSeqs;
            [DataMember(Name = "action_types")]
            public System.Collections.Generic.List<int> ActionTypes;
            [DataMember(Name = "qs")]
            public System.Collections.Generic.List<int> Qs;
            [DataMember(Name = "rs")]
            public System.Collections.Generic.List<int> Rs;

            public SubmitIntentBatch(
                string Wallet,
                System.Collections.Generic.List<string> IntentIds,
                System.Collections.Generic.List<long> ClientSeqs,
                System.Collections.Generic.List<int> ActionTypes,
                System.Collections.Generic.List<int> Qs,
                System.Collections.Generic.List<int> Rs
            )
            {
                this.Wallet = Wallet;
                this.IntentIds = IntentIds;
                this.ClientSeqs = ClientSeqs;
                this.ActionTypes = ActionTypes;
                this.Qs = Qs;
                this.Rs = Rs;
            }

            public SubmitIntentBatch()
            {
                this.Wallet = "";
                this.IntentIds = new();
                this.ClientSeqs = new();
                this.ActionTypes = new();
                this.Qs = new();
                this.Rs = new();
            }

            string IReducerArgs.ReducerName => "submit_intent_batch";
        }
    }
}
