// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SubmitIntentHandler(ReducerEventContext ctx, string intentId, string wallet, long clientSeq, int actionType, int q, int r);
        public event SubmitIntentHandler? OnSubmitIntent;

        public void SubmitIntent(string intentId, string wallet, long clientSeq, int actionType, int q, int r)
        {
            conn.InternalCallReducer(new Reducer.SubmitIntent(intentId, wallet, clientSeq, actionType, q, r));
        }

        public bool InvokeSubmitIntent(ReducerEventContext ctx, Reducer.SubmitIntent args)
        {
            if (OnSubmitIntent == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSubmitIntent(
                ctx,
                args.IntentId,
                args.Wallet,
                args.ClientSeq,
                args.ActionType,
                args.Q,
                args.R
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SubmitIntent : Reducer, IReducerArgs
        {
            [DataMember(Name = "intent_id")]
            public string IntentId;
            [DataMember(Name = "wallet")]
            public string Wallet;
            [DataMember(Name = "client_seq")]
            public long ClientSeq;
            [DataMember(Name = "action_type")]
            public int ActionType;
            [DataMember(Name = "q")]
            public int Q;
            [DataMember(Name = "r")]
            public int R;

            public SubmitIntent(
                string IntentId,
                string Wallet,
                long ClientSeq,
                int ActionType,
                int Q,
                int R
            )
            {
                this.IntentId = IntentId;
                this.Wallet = Wallet;
                this.ClientSeq = ClientSeq;
                this.ActionType = ActionType;
                this.Q = Q;
                this.R = R;
            }

            public SubmitIntent()
            {
                this.IntentId = "";
                this.Wallet = "";
            }

            string IReducerArgs.ReducerName => "submit_intent";
        }
    }
}
