// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TradeCreateHandler(ReducerEventContext ctx, string owner, int giveWood, int giveFood, int giveMinerals, int wantWood, int wantFood, int wantMinerals, long expiresInCycles);
        public event TradeCreateHandler? OnTradeCreate;

        public void TradeCreate(string owner, int giveWood, int giveFood, int giveMinerals, int wantWood, int wantFood, int wantMinerals, long expiresInCycles)
        {
            conn.InternalCallReducer(new Reducer.TradeCreate(owner, giveWood, giveFood, giveMinerals, wantWood, wantFood, wantMinerals, expiresInCycles));
        }

        public bool InvokeTradeCreate(ReducerEventContext ctx, Reducer.TradeCreate args)
        {
            if (OnTradeCreate == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTradeCreate(
                ctx,
                args.Owner,
                args.GiveWood,
                args.GiveFood,
                args.GiveMinerals,
                args.WantWood,
                args.WantFood,
                args.WantMinerals,
                args.ExpiresInCycles
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TradeCreate : Reducer, IReducerArgs
        {
            [DataMember(Name = "owner")]
            public string Owner;
            [DataMember(Name = "give_wood")]
            public int GiveWood;
            [DataMember(Name = "give_food")]
            public int GiveFood;
            [DataMember(Name = "give_minerals")]
            public int GiveMinerals;
            [DataMember(Name = "want_wood")]
            public int WantWood;
            [DataMember(Name = "want_food")]
            public int WantFood;
            [DataMember(Name = "want_minerals")]
            public int WantMinerals;
            [DataMember(Name = "expires_in_cycles")]
            public long ExpiresInCycles;

            public TradeCreate(
                string Owner,
                int GiveWood,
                int GiveFood,
                int GiveMinerals,
                int WantWood,
                int WantFood,
                int WantMinerals,
                long ExpiresInCycles
            )
            {
                this.Owner = Owner;
                this.GiveWood = GiveWood;
                this.GiveFood = GiveFood;
                this.GiveMinerals = GiveMinerals;
                this.WantWood = WantWood;
                this.WantFood = WantFood;
                this.WantMinerals = WantMinerals;
                this.ExpiresInCycles = ExpiresInCycles;
            }

            public TradeCreate()
            {
                this.Owner = "";
            }

            string IReducerArgs.ReducerName => "trade_create";
        }
    }
}
