// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TradeAcceptHandler(ReducerEventContext ctx, ulong offerId, string accepter);
        public event TradeAcceptHandler? OnTradeAccept;

        public void TradeAccept(ulong offerId, string accepter)
        {
            conn.InternalCallReducer(new Reducer.TradeAccept(offerId, accepter));
        }

        public bool InvokeTradeAccept(ReducerEventContext ctx, Reducer.TradeAccept args)
        {
            if (OnTradeAccept == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTradeAccept(
                ctx,
                args.OfferId,
                args.Accepter
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TradeAccept : Reducer, IReducerArgs
        {
            [DataMember(Name = "offer_id")]
            public ulong OfferId;
            [DataMember(Name = "accepter")]
            public string Accepter;

            public TradeAccept(
                ulong OfferId,
                string Accepter
            )
            {
                this.OfferId = OfferId;
                this.Accepter = Accepter;
            }

            public TradeAccept()
            {
                this.Accepter = "";
            }

            string IReducerArgs.ReducerName => "trade_accept";
        }
    }
}
