// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TradeCancelHandler(ReducerEventContext ctx, ulong offerId, string requester);
        public event TradeCancelHandler? OnTradeCancel;

        public void TradeCancel(ulong offerId, string requester)
        {
            conn.InternalCallReducer(new Reducer.TradeCancel(offerId, requester));
        }

        public bool InvokeTradeCancel(ReducerEventContext ctx, Reducer.TradeCancel args)
        {
            if (OnTradeCancel == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTradeCancel(
                ctx,
                args.OfferId,
                args.Requester
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TradeCancel : Reducer, IReducerArgs
        {
            [DataMember(Name = "offer_id")]
            public ulong OfferId;
            [DataMember(Name = "requester")]
            public string Requester;

            public TradeCancel(
                ulong OfferId,
                string Requester
            )
            {
                this.OfferId = OfferId;
                this.Requester = Requester;
            }

            public TradeCancel()
            {
                this.Requester = "";
            }

            string IReducerArgs.ReducerName => "trade_cancel";
        }
    }
}
